services:
  server:
    build:
      context: .
    environment:
      DATABASE_DEVELOPMENT: ${DATABASE_DEVELOPMENT}
      DATABASE_TEST: ${DATABASE_TEST}
      DATABASE_PRODUCTION: ${DATABASE_PRODUCTION}
      SECRET_KEY: ${SECRET_KEY}
      CAROLINA_USER: ${CAROLINA_USER}
      CAROLINA_PASSWORD: ${CAROLINA_PASSWORD}
    secrets:
      - db_development
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: .

secrets:
  db_development:
    environment: DATABASE_DEVELOPMENT
