services:
  server:
    build:
      context: .
    environment:
      DATABASE_DEVELOPMENT: ${DATABASE_DEVELOPMENT}
    secrets:
      - db_development
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: .

secrets:
  db_development:
    environment: DATABASE_DEVELOPMENT
